config/routes.rb
Base::Application.routes.draw do

  resources :server_side, only: [:index, :show]
  resources :hybrid,      only: [:index, :show]
  resources :client_side, only: [:index, :show]

  root to: "home#index"
end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/client_side_controller.rb
class ClientSideController < ApplicationController
  expose(:contents)

  def index
    @contents = Content.all
    gon.rabl template: 'app/views/contents/contents.rabl'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  expose(:contents)

  def index; end
end

app/controllers/hybrid_controller.rb
class HybridController < ApplicationController
  expose(:contents)
  expose(:content)

  def index
    @contents = Content.all
    gon.rabl template: 'app/views/contents/contents.rabl'
  end

  def show; end
end

app/controllers/server_side_controller.rb
class ServerSideController < ApplicationController
  expose(:contents)
  expose(:content)

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/client_side/index.slim
= javascript_tag "currentState = 'client_side'"

app/views/client_side/show.slim
= javascript_tag "currentState = 'client_side'"

app/views/home/index.slim
= render "shared/menu"

app/views/hybrid/index.slim
= render 'shared/contents', mustache: { contents: contents.as_json }
= javascript_tag "currentState = 'hybrid'"

app/views/hybrid/show.slim
= render 'shared/item', mustache: content
= javascript_tag "currentState = 'hybrid'"

app/views/layouts/application.slim
doctype 5

html
  head
    title Base
    = stylesheet_link_tag    "application", media: "all"
    = csrf_meta_tags
    = include_gon
    meta content="OMGHR3WTBbNpVVWOMK5Jxe2aGtB1r_v4R8LaB3psQS4" name="google-site-verification"
  body
    #wrapper
      = render 'shared/menu'
      #page-wrapper
        = yield

  = javascript_tag "firstLoad = true;"
  = javascript_include_tag "application"

app/views/server_side/index.slim
.row
  - for content in contents
    .col-lg-3
      .panel.panel-info
        .panel-heading
          .row
            .col-xs-6
              img src="#{content.img_standard_resolution}"
            .col-xs-6.text-right
              p.announcement-heading = content.likes
              p.announcement-text Likes!
        a href="#{server_side_path(content)}"
          .panel-footer.announcement-bottom
            .row
              .col-xs-6
                | View more
              .col-xs-6.text-right
                i.fa.fa-arrow-circle-right

app/views/server_side/show.slim
img src="#{content.img_standard_resolution}"
  .description
    p #{content.caption}
    p Likes: #{content.likes}
    p Comments: #{content.comments}
  .author
    img src="#{content.user_icon}" style="max-width:50px;"
      p #{content.user_name}

app/views/shared/_menu.slim
nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
  /! Brand and toggle get grouped for better mobile display
  .navbar-header
    button.navbar-toggle data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button"
      span.sr-only Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar
    a.navbar-brand href="index.html"
  /! Collect the nav links, forms, and other content for toggling
  .collapse.navbar-collapse.navbar-ex1-collapse
    ul.nav.navbar-nav.side-nav
      li
        a href="#{server_side_index_path}"
          i.fa.fa-bar-chart-o
          | 100% Server Side
      li
        a href="#{client_side_index_path}"
          i.fa.fa-bar-chart-o
          | 100% Client Side
      li
        a href="#{hybrid_index_path}"
          i.fa.fa-bar-chart-o
          | Hybrid - Shared templates strategy